name: Rust Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Collect coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Publish coverage to Codecov
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v3.1.1
        with:
          verbose: true
          fail_ci_if_error: true
